---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Verify web server is running
      ansible.builtin.uri:
        url: http://localhost/
        status_code: 200
        return_content: true
        headers:
          Host: auth.example.ci
      register: result_get_auth_portal
    - name: Debug
      ansible.builtin.debug:
        msg: '{{ result_get_auth_portal }}'
    - name: Check if LemonLDAP is present into response
      ansible.builtin.assert:
        that:
          - "'LemonLDAP' in result_get_auth_portal.content"
