---
# Use shared config under .config/molecule at the root of this project
platforms:
  - name: rockylinux9
    image: rockylinux:9
    command: /lib/systemd/systemd
    privileged: true
    pre_build_image: false
    cgroupns_mode: host
    dockerfile: ../../.config/molecule/Dockerfile.j2
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
  - name: debian11
    image: debian:bullseye-slim
    command: /lib/systemd/systemd
    privileged: true
    pre_build_image: false
    cgroupns_mode: host
    dockerfile: ../../.config/molecule/Dockerfile.j2
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
  - name: debian12
    image: debian:bookworm-slim
    command: /lib/systemd/systemd
    privileged: true
    pre_build_image: false
    cgroupns_mode: host
    dockerfile: ../../.config/molecule/Dockerfile.j2
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
