---
- name: Prepare
  hosts: all
  vars:
    lemonldap_domain: example.ci
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false
    - name: Install GPG
      apt:
        name: gpg
        state: present
      when: ansible_os_family == 'Debian'
      changed_when: false
  roles:
    - role: worteks.lemonldap.install
