---
- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present

- name: Install LLNG Repository KEY
  copy:
    src: rpm-gpg-key-ow2
    dest: /tmp/gpg-key-ow2
    owner: root
    group: root
    mode: 0644

- name: Import LLNG GPG KEY
  apt_key:
    file: /tmp/gpg-key-ow2
    state: present

- name: Install LLNG Debian Repository
  copy:
    src: debian_lemonldap-ng.list
    dest: /etc/apt/sources.list.d/lemonldap-ng.list
    owner: root
    group: root
    mode: 0644
  register: llng_repo

- name: Install Webserver and dependencies
  ansible.builtin.package:
    update_cache: true
    name: '{{ __debian_pkgs }}'
    state: present

- name: Enable Apache
  service:
    name: apache2
    state: started
    enabled: true
  when: lemonldap_webserver | default('apache') in [ 'apache', 'httpd' ]

- name: Enable Nginx
  service:
    name: nginx
    state: started
    enabled: true
  when: lemonldap_webserver | default('apache') == 'nginx'
