---
- name: Install apt-transport-https
  ansible.builtin.apt:
    name: apt-transport-https
    state: present

- name: Install LLNG Repository KEY
  ansible.builtin.copy:
    src: deb-gpg-key-ow2
    dest: /tmp/gpg-key-ow2
    owner: root
    group: root
    mode: 0644

- name: Import LLNG GPG KEY
  ansible.builtin.apt_key:
    file: /tmp/gpg-key-ow2
    state: present

# Defined in defaults/main.yml
- name: Install LLNG Debian Repository
  ansible.builtin.apt_repository:
    repo: '{{ item }}'
    state: present
    filename: lemonldap-ng.list
  loop: '{{ lemonldap_apt_repositories }}'
  register: llng_repo

- name: Install Webserver and dependencies
  ansible.builtin.package:
    update_cache: true
    name: '{{ __debian_pkgs }}'
    state: present

- name: Enable Apache
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: true
  when: lemonldap_webserver | default('apache') in [ 'apache', 'httpd' ]

- name: Enable Nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
  when: lemonldap_webserver | default('apache') == 'nginx'
